Bug 1806899 - Detect link escapes in safe_extract
mozilla-releng/tooltool pull request #1077
Opened 2023-02-16 20:24 UTC by gbrownmozilla

2023-02-16 20:33 UTC, gbrownmozilla commented
@jcristau I recall you said this approach wouldn't always work, but I can't think of why, and it detects these test cases.

2023-02-20 14:00 UTC, jcristau requested changes
I believe this rejects harmless symlinks and potentially doesn't catch ones that do escape.

2023-02-21 22:19 UTC, gbrownmozilla commented on client/tooltool.py
> +        link_path = os.path.join(path, member.linkname)
Yes, thanks for catching that.

2023-02-21 23:47 UTC, gbrownmozilla commented
Sorry, messed up the merge...let's just start over...

2023-02-21 23:47 UTC, closed without merging